<?php

namespace Database\Seeders;

use App\Models\TipoDocumento;
use Illuminate\Database\Seeder;

class TipoDocumentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tiposDocumentos = [
            [
                'nombre' => 'Inscripcion de faena (Direccion del Trabajo)',
                'codigo' => 'INSCRIPCION_FAENA',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 15120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'F30 (Direccion del Trabajo)',
                'codigo' => 'F30',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 15120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'F30-1 (Direccion del Trabajo)',
                'codigo' => 'F30_1',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 15120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Planillas de cotizaciones previsionales pagadas',
                'codigo' => 'PLANILLAS_COTIZACIONES',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 15120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Copia del F-29 pagado, del mes anterior',
                'codigo' => 'F29',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 15120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Libro de remuneraciones',
                'codigo' => 'LIBRO_REMUNERACIONES',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 10240,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Comprobante Reglamento Interno actualizado (Direccion del Trabajo y Seremi)',
                'codigo' => 'REGLAMENTO_INTERNO',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Certificado de adhesion a la mutualidad',
                'codigo' => 'ADHESION_MUTUAL',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Listado actualizado del personal que participara en el servicio',
                'codigo' => 'LISTADO_PERSONAL',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Procedimiento de trabajo seguro especifico a la labor a ejecutar',
                'codigo' => 'PROCEDIMIENTO_TRABAJO_SEGURO',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Evidencia de trabajo en protocolos MINSAL aplicables a la empresa',
                'codigo' => 'EVIDENCIA_PROTOCOLS_MINSAL',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Protocolo LEY KARIN implementado en la empresa, con registro de firma de todos los trabajadores',
                'codigo' => 'PROTOCOLO_LEY_KARIN',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Copia contrato de trabajo',
                'codigo' => 'CONTRATO_TRABAJO',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Copia de cedula de identidad vigente',
                'codigo' => 'CEDULA_IDENTIDAD',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Copia libro de asistencia',
                'codigo' => 'LIBRO_ASISTENCIA',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Copia liquidaciones de sueldo',
                'codigo' => 'LIQUIDACIONES_SUELDO',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Comprobante de entrega del Reglamento Interno',
                'codigo' => 'ENTREGA_REGLAMENTO_INTERNO',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Entrega de Informacion de Riesgos Laborales (IRL)',
                'codigo' => 'IRL',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Registro de entrega de EPP',
                'codigo' => 'ENTREGA_EPP',
                'descripcion' => null,
                'periodicidad' => 'mensual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => 10,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Comprobante de capacitacion sobre el plan de emergencias de la empresa. Antes de iniciar trabajos.',
                'codigo' => 'CAPACITACION_PLAN_EMERGENCIAS',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => true,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Matriz de riesgo',
                'codigo' => 'MATRIZ_RIESGO',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Comprobante del registro de capacitacion sobre el procedimiento de trabajo seguro especifico al servicio a realizar',
                'codigo' => 'CAPACITACION_PROCEDIMIENTO_TRABAJO_SEGURO',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Plan de emergencias',
                'codigo' => 'PLAN_EMERGENCIAS',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Revisiones tecnicas y permisos de circulacion de los vehiculos',
                'codigo' => 'REVISIONES_TECNICAS_PERMISOS',
                'descripcion' => null,
                'periodicidad' => 'anual',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => 30,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
            [
                'nombre' => 'Letrero de identificacion contratista de color amarillo',
                'codigo' => 'LETRERO_IDENTIFICACION',
                'descripcion' => null,
                'periodicidad' => 'unico',
                'es_obligatorio' => true,
                'es_documento_trabajador' => false,
                'dias_vencimiento' => null,
                'formatos_permitidos' => ['pdf'],
                'tamano_maximo_kb' => 5120,
                'requiere_validacion' => true,
                'instrucciones' => null,
                'activo' => true,
            ],
        ];

        foreach ($tiposDocumentos as $tipo) {
            TipoDocumento::query()->updateOrCreate(
                ['codigo' => $tipo['codigo']],
                $tipo,
            );
        }

        $this->command->info('Created '.count($tiposDocumentos).' document types.');
    }
}
